rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - rbx-2.0
  - jruby
  - ree
gemfile:
  - gemfiles/Gemfile.rails3_0
  - gemfiles/Gemfile.rails3_1
script: "export DISPLAY=:99.0 && bundle exec rake spec"
before_script: "sh -e /etc/init.d/xvfb start"